import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import MyProvider from "@/myProvider/MyProvider";
import CartProvider from '@/context/cart.context'
import { ThemeProvider } from 'next-themes'






export const metadata: Metadata = {
  title: "Trendy Buy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    <html suppressHydrationWarning lang="en">
      <body className="" >
         <ThemeProvider attribute={'class'} defaultTheme="light">
           <MyProvider >
          <CartProvider>

        <Navbar/> 
        <div className="   py-3  ">
          <Toaster />

          {children}

        </div>
        <Footer/>

           </CartProvider>
        </MyProvider>
      
    </ThemeProvider>
        


    
       
   
      </body>
    </html>
 </> ;
}
